[echo]
listen = "0.0.0.0:8080"
[jwt]
exp = 6
secret = "GfK@boqLRaGrce2Q"
[admin]
user = "root"
password = "M@hLuxY5y$P7cyQh"
[mysql]
host = "172.30.31.54"
port = 30759
user = "root"
password = "gQ9oww2tua"
database = "beaconglobal"
max_idle_conn = 10
max_open_conn = 5

[Database]
Host = "172.30.31.54"
Port = 30759
LogMode = true
Username = "root"
Password = "gQ9oww2tua"
Database = "spider"

[ClickHouse]
Host = "127.0.0.1"
Port = "9000"
UserName = "default"
Password = "123456"
Database = "ethDatas"
ReadTimeout = "10"
WriteTimeout = "20"
BlockSize = "1000"
DeBug = "false"
FlushPeriod = "2s"

[Server]
Port = "9527"
SummedCheck = true
VerifyHost = "http://127.0.0.1:8080/"

[Ethereum]
URL = "https://mainnet.infura.io/v3/2da8854f387e471f9063be2848f6f9a2"
Chain = "ETH"
ApiGetGasPrice = true
AddrLimit = 100
ConfirmHeight = 12
MinGasPrice = 10
MaxGasPrice = 1000
ERC20GasLimit = 80000

Debug = false
Notice = true

[LogConfig]
  Path = ""
  Level = ""